### ISSUE TITLE
Using NHibernate.AspNet.Identity with Identity Core

### ISSUE THREAD

**Issue by dhughes55** [nhibernate/NHibernate.AspNet.Identity#63]
Hi.  Does anyone know if there plans for NHibernate.AspNet.Identity to support .NET core now that NHibernate supports it?

(see http://nhibernate.info/blog/2018/03/17/nhibernate-5-1-released.html for more info)

**Comment by lnu** [comment]
It's not only about migrating to .net core. There is a new version of [asp.net identity](https://github.com/aspnet/Identity) for .net core.
Nothing has been started yet for this.

**Comment by beginor** [comment]
@dhughes55 I have started a [nhibernate-extensions](https://github.com/beginor/nhibernate-extensions) repo, and it will have an asp.net core provider for nhibernate.

when it is completed, will publish it to nuget.

**Comment by beginor** [comment]
ASPNET Core Identity provider that uses NHibernate for storage https://github.com/beginor/nhibernate-extensions#nhibernateextensionsaspnetcoreidentity

**Comment by beginor** [comment]
https://www.nuget.org/packages/NHibernate.Extensions.AspNetCore.Identity

**Comment by fredericDelaporte** [comment]
@lnu, on the dev mailing list [here](https://groups.google.com/forum/#!topic/nhibernate-development/u7s0qH4iaOE), @roryplaire asks for publishing its own NHibernate.AspNetCore.Identity package, currently having its sources hosted in https://github.com/esha/NHibernate.AspNetCore.Identity.
And also, would it be ok for you to eventually add it as a new nhibernate repository, since asp.net identity has quite changed for .Net Core?

@beginor, it could be done your version instead, likely renamed `NHibernate.AspNetCore.Identity` in such case, provided you are currently committed to maintain it. It could be even better if you and @roryplaire are both interested in and collaborate to a `nhibernate/NHibernate.AspNetCore.Identity` repository, provided this suits @lnu too.

**Comment by beginor** [comment]
@fredericDelaporte It's my pleasure if I can use the name of `NHibernate.AspNetCore.Identity`.

**Comment by lnu** [comment]
@fredericDelaporte Looks good to me. It's nice other people are working on the identity provider for asp.net core.  I also think it needs a new repo as the versions don't have the same target.

@beginor I have no idea if it should be renamed. In this case, maybe we should keep the name consistent with the previous provider.

**Comment by beginor** [comment]
@fredericDelaporte if there is a `nhibernate/NHibernate.AspNetCore.Identity` repo , I will be very glad to push my code to it. 

I have use nhibernate in my work for many years, and I think I will maintain it as I continue to use nhibernate.

**Comment by fredericDelaporte** [comment]
I have created the repository and added @beginor to nhibernate-aspnet-identity team members, which I have setup as admin of the new repository. (It is also admin of NHibernate.AspNet.Identity repository.)

**Comment by beginor** [comment]
@fredericDelaporte thanks, I will push the repo soon later

**Comment by dhughes55** [comment]
You guys rock!
